### ISSUE TITLE
GTEnumerator performance

### ISSUE THREAD

**Issue by rowanj** [libgit2/objective-git#187]
One of my longest-running tasks on rowanj/gitx (OS X Git GUI) is to replace the parsing of command-line `git` output with libgit2 and Objective-Git.

I've recently got a working branch which replaces the loading of the commit info from `git log` with `GTEnumerator`, but I've noticed that it's taking around 1.5x the time to load the same commits (isolating the parsing/enumeration thread).

Running on a clone of the mainline Linux repo, generating and parsing the command line output took around 10s total; but the `GTEnumerator` approach is taking around 12s in `git_revwalk_next` (close enough that it doesn't really matter), but then another 4.5s in `-[GTRepository lookupObjectBySha:objectType:error:]`

```
pom-pom:linux rowan$ time (git log --branches --remotes --tags > /dev/null)

real	0m10.872s
user	0m9.665s
sys	0m0.914s
```
![screen shot 2013-06-18 at 10 22 41 am](https://f.cloud.github.com/assets/47049/665897/5e655f1c-d7af-11e2-95ef-b29015bd470b.png)

**Comment by joshaber** [comment]
This is super old and probably not applicable anymore.
