### ISSUE TITLE
Better Documentation (Quickstart)

### ISSUE THREAD

**Issue by kaylarose** [libgit2/objective-git#30]
Objective-Git should really have a 5-minute quickstart to using the Objective-Git framework in an new/existing XCode project. The framework article linked to in the README is okay as a generic guide to frameworks, but not really for using Objective-Git specifically.

##### For Instance:
* Drag X to Linked Frameworks
* Modify Y build settings in the target Info Window
* Link Z dependencies
* Etc. Etc. Etc.

        #import <ObjectiveGit/ObjectiveGit.h>

##### Other examples of good Quickstarts:
* http://brandonwalkin.com/bwtoolkit/ (install guide section)
* https://github.com/geoffgarside/Git.framework

**Comment by phatblat** [comment]
Resolved with #503
