### ISSUE TITLE
Trying to build update_libssl_ios failing

### ISSUE THREAD

**Issue by M0rph3v5** [libgit2/objective-git#304]
script/update_libssl_ios: line 47: ./Configure: No such file or directory

I did everything according to the readme on https://github.com/libgit2/objective-git

Adding it to an iOS project, setup the search paths. Ran the bootstrap before all that.

Any ideas?

PS. Also tried the cocoapod which gives a shitload of errors from the libgit2. Seems like an older version.

**Comment by phatblat** [comment]
Stale issue, closing. If this issue is still occurring in the current version, please include the log details so it can be diagnosed. Thanks!
