### ISSUE TITLE
GTRepository cloneFromURL: Operation not permitted

### ISSUE THREAD

**Issue by mindintransit** [libgit2/objective-git#313]
I'm working on an application which needs to clone a remote repository. Below is a simplified version of the code I'm using:

```objective-c
NSURL *repoUrl = [NSURL URLWithString:@"https://<github-url-or-similar>"];
NSURL *pathUrl = [NSURL URLWithString:@"<local-file-system-path-from-user-input>"];

[GTRepository cloneFromURL:repoUrl toWorkingDirectory:pathUrl options:NULL error:&error transferProgressBlock:NULL checkoutProgressBlock:NULL];
```

This is generating the following error:
```
Error Domain=GTGitErrorDomain Code=-1 "Failed to clone repository from <removed> to <removed> UserInfo=<removed> {NSLocalizedDescription=Failed to clone repository from <removed> to <removed>, NSUnderlyingError=0x60800024e700 "Failed to connect to github.com: Operation not permitted"}
```

This looks like some kind of permission error in that the application is now allowed to make an outgoing connection to the remote repository. I work in fairly restrictive (corporate locked down) environment but I am able to run git commands from the CLI as both normal and sudo users without issue (although I do  need to specify http_proxy and https_proxy in my bash profile).

Can anyone shed any light on whether the error I'm seeing is due to my corporate network environment or if it's just down to me doing something wrong? Either way - are there any solutions to the problem I'm seeing (the final application will have to run in this network environment so workarounds during the dev process won't solve the problem)?

Thanks!

**Comment by phatblat** [comment]
@thelucid Credentials are provided using `GTCredentialProvider`. The tests include an example of providing [SSH credentials](https://github.com/libgit2/objective-git/blob/master/ObjectiveGitTests/GTRepositorySpec.m#L139-L178).

HTTP credentials are much simpler to provide using `+[GTCredential credentialWithUserName:password:error:`.
