### ISSUE TITLE
libiconv linker errors

### ISSUE THREAD

**Issue by Uncommon** [libgit2/objective-git#373]
I'm synced to c2d3af2f25ede439e588596d408269551ab0b169 (current master), and I've run the bootstrap script and tried cleaning, but I always get these linker errors when building the framework target:

```
Undefined symbols for architecture x86_64:
  "_libiconv", referenced from:
      _git_path_iconv in libgit2.a(path.c.o)
  "_libiconv_close", referenced from:
      _git_path_iconv_clear in libgit2.a(path.c.o)
  "_libiconv_open", referenced from:
      _git_path_iconv_init_precompose in libgit2.a(path.c.o)
```

**Comment by soniccat** [comment]
Had the same problem. Noticed that after launching ./script/update_libgit2 I had this line:
```-- Found Iconv: -L/opt/local/lib -liconv```
it means that it took wrong lib. 
After deactivating the lib 
```sudo port -f deact libiconv```
I saw the right path
```-- Found Iconv: -L/usr/lib -liconv```
And the problem was solved

**Comment by joshaber** [comment]
Pretty old and we've recently cleaned up the libgit2 building process: #483
