### ISSUE TITLE
Assertion failed while calling GTRepository cloneFromURL on iOS

### ISSUE THREAD

**Issue by abhishiv** [libgit2/objective-git#400]
Hey guys

I just started using objective-git and am a bit struggling with it. I am using the latest on master right now, Basically, if I do

```
NSURL *url = [NSURL URLWithString:@"https://github.com/libgit2/objective-git.git"];
GTRepository *repo = [GTRepository cloneFromURL:url toWorkingDirectory:dir options:NULL  error:&error transferProgressBlock:NULL checkoutProgressBlock:NULL];
```

it throws up

```
Assertion failed: (git_atomic_get(&git__n_inits) > 0), function git__global_state, file /Users/xyz/project/platforms/ios/objective-git/External/libgit2/src/global.c, line 274
```

The stack trace looks like this

```
0  0x02aa5952 in __pthread_kill ()
1  0x02a69167 in pthread_kill ()
2  0x027d89c9 in abort ()
3  0x027a353b in __assert_rtn ()
4  0x000a23d0 in git__global_state at objective-git/External/libgit2/src/global.c:274
5  0x00098c57 in set_error at objective-git/External/libgit2/src/errors.c:23
6  0x00098c02 in giterr_set at objective-git/External/libgit2/src/errors.c:74
7  0x0007b608 in config_delete at objective-git/External/libgit2/src/config_file.c:611
8  0x00078193 in git_config_delete_entry at objective-git/External/libgit2/src/config.c:606
9  0x000fdc59 in repo_init_fs_configs at objective-git/External/libgit2/src/repository.c:968
10 0x000fea24 in repo_init_config at objective-git/External/libgit2/src/repository.c:1015
11 0x000fe16b in git_repository_init_ext at objective-git/External/libgit2/src/repository.c:1484
12 0x000fdf1e in git_repository_init at objective-git/External/libgit2/src/repository.c:1446
13 0x00072308 in default_repository_create at objective-git/External/libgit2/src/clone.c:238
14 0x0007201b in git_clone at objective-git/External/libgit2/src/clone.c:436
15 0x00026102 in +[GTRepository cloneFromURL:toWorkingDirectory:options:error:transferProgressBlock:checkoutProgressBlock:] at objective-git/Classes/GTRepository.m:266
```

I'm not a full time objective-c developer, so I might be wrong, but the stack trace makes it seem that `git_config_delete_entry(cfg, "core.symlinks") < 0` in `repo_init_fs_configs` is the cause of it.

**Comment by wvaughn409** [comment]
> `git_threads_init` is invoked in [an `__attribute__((constructor))` function](https://github.com/libgit2/objective-git/blob/8de13f8189f2d3e1106eaa36f915c96c35096455/Classes/ObjectiveGit.m) automatically, so you don't have to call it explicitly.
> 
> However, for functions like that to be run like they're supposed to, you have to [link with `-all_load`](https://github.com/libgit2/objective-git#importing-objectivegit-on-ios). Is that in your project's linker flags?

Hello. I am having this problem also. I do not understand where in the visual studio 2019 linker options to specify "-all_load". Could you help me with this please?
