### ISSUE TITLE
Mark designated initialisers with NS_DESIGNATED_INITIALIZER

### ISSUE THREAD

**Issue by pbendersky** [libgit2/objective-git#406]
This hints the compiler to give warnings if another init method, or subclass doesn't call the designated initializer.

**Comment by phatblat** [comment]
For reference on NS_DESIGNATED_INITIALIZER: https://developer.apple.com/library/ios/releasenotes/ObjectiveC/ModernizationObjC/AdoptingModernObjective-C/AdoptingModernObjective-C.html#//apple_ref/doc/uid/TP40014150-CH1-SW8

**Comment by phatblat** [comment]
Closing now that #449 is merged.
