### ISSUE TITLE
Objective-Git should use value objects

### ISSUE THREAD

**Issue by mdiep** [libgit2/objective-git#407]
## The Idea
Objective-Git should be designed to work inside Cocoa apps, which are usually concurrent and long-lived. Since the data on disk can always change underneath you, the API needs to balance these properties:

1. **Staleness**: Data in the app may not reflect the data on disk. Has an object been deleted, renamed, or otherwise altered?

2. **Consistency**: It may be hard to get a consistent view of all the data. Can you retrieve multiple properties from an object and have them be in sync?

3. **Contention**: It may be hard to group access to the database, so reads could happen everywhere and everywhere.

4. **Simplicity**: Is it obvious what a given API will do? e.g., Is it obvious which properties result in disk access? Does `-[GTBranch SHA]` get the latest SHA from the disk?

The current design of Objective-Git prioritizes (1) and makes (2), (3), and (4) more difficult. Many Objective-Git objects are just thin wrappers around their libgit2 counterparts, and the properties are just wrappers around libgit2 functions. It's hard to tell which properties result in lookups, complicating contention and consistency.

If, instead, we used immutable value objects, then (2), (3), and (4) are substantially easier, and (1) is not substantially more difficult. Concurrency would be much simpler because these objects could be passed around and used freely.

## The Changes
These are the classes I have in mind as values (but I haven't looked closely at every Objective-Git class, so this may not be exhaustive):

* `GTBlob`
* `GTBranch`
* `GTCommit`
* `GTRemote`
* `GTSignature`
* `GTTree`
* `GTTag`

Practically, here are the changes that would be required:

0. Make all the properties on these objects either be (a) synthesized or (b) computed from another immutable, synthesized property. (Some properties would need to be removed and made into methods.)

0. Remove references to the `GTRepository` from all these objects. Move any APIs that depend on the `GTRepository` to a method on `GTRepository`.

0. Move methods from these objects to `GTRepository`. (Usually a method means reading from or writing to the repository.)

@jspahrsummers said there's some problems with this general idea, but I'm not sure what they are.

**Comment by phatblat** [comment]
@mdiep Any reason to keep this issue open? Does [SwiftGit2](https://github.com/SwiftGit2) address this?

**Comment by mdiep** [comment]
I think SwiftGit2 addresses this. 👍
