### ISSUE TITLE
0.6 won't build

### ISSUE THREAD

**Issue by pietbrauer** [libgit2/objective-git#442]
When trying to build the 0.6 release I always get the following error when trying to execute `script/update_libgit2_ios` although `libssh2` and `openssl` built successful.

[jspahrsummers seems to have the same problem](https://twitter.com/jspahrsummers/status/566824855794761728)

```
[ 90%] Building C object CMakeFiles/git2.dir/src/transports/smart_protocol.c.o
[ 91%] Building C object CMakeFiles/git2.dir/src/transports/ssh.c.o
/Users/piet.brauer/Documents/Projekte/iOS/objective-git-build/Carthage/Checkouts/objective-git/External/libgit2/src/transports/ssh.c:9:10: fatal error: 'libssh2.h' file not found
#include <libssh2.h>
         ^
1 error generated.
make[2]: *** [CMakeFiles/git2.dir/src/transports/ssh.c.o] Error 1
make[1]: *** [CMakeFiles/git2.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by phatblat** [comment]
Same here. I was able to get it to build by defining LIBSSH2_INCLUDE_DIR. 

See https://github.com/phatblat/objective-git/commit/b817e13e4c29bea355044e316d9214fbc955ac8f

I had to make a similar change to get the Mac build to work but haven't included these changes in a pull request yet.

**Comment by pietbrauer** [comment]
@phatblat Nice work! I so look forward to have prebuilt frameworks with Carthage!!

**Comment by pietbrauer** [comment]
@phatblat Worked for me.

**Comment by jspahrsummers** [comment]
Could one of you please open a PR for this? :pray:
