### ISSUE TITLE
iOS Tests

### ISSUE THREAD

**Issue by phatblat** [libgit2/objective-git#444]
Is there interest (besides myself) in having the tests runnable on iOS? It looks like the only thing stopping this is the current implementation of -unzipFile:fromArchiveAtPath:intoDirectory: which uses NSTask to shell out to the unzip command.

This could be implemented in-process on iOS using SSZipArchive or straight libz function calls (to minimize dependencies).

**Comment by alehed** [comment]
To me iOS tests don't seem necessary, I get the confidence that it's working from running the OS X tests.

**Comment by phatblat** [comment]
Closing as this is being worked in #484
