### ISSUE TITLE
Apply an stash to a repository

### ISSUE THREAD

**Issue by AustinChou** [libgit2/objective-git#453]
In the example of  `GTRepository+Stashing.h` and `GTRepositoryStashingSpec.m`, I can use objective-git to create and enumerate stashes, but I found that there is no way to apply any stash. I don't know why there haven't such an API to do that. So could you add that feature during your next shipping?

**Comment by joshaber** [comment]
This functionality doesn't yet exist in libgit2 (which is what objective-git wraps).

There's currently a PR open which adds it: https://github.com/libgit2/libgit2/pull/3018. Once that lands in libgit2, we'd welcome a PR which exposes it through objective-git :sparkles:

**Comment by tiennou** [comment]
(which I happen to have lying around, but it's waiting on libgit2 support)

**Comment by joshaber** [comment]
:sparkling_heart: @tiennou :metal:

**Comment by phatblat** [comment]
libgit2/libgit2#3018 was merged on May 12 and we've bumped libgit2 a couple times since then, so I suspect this request is no longer blocked.

@tiennou do you feel like taking this on?

**Comment by tiennou** [comment]
#501 ! As I said there I might or might not have the time to setup tests for this, but feel free to use that as a basis.

**Comment by phatblat** [comment]
Closing as #501 has been merged.
