### ISSUE TITLE
Objective-Git can't be built on 10.9 anymore

### ISSUE THREAD

**Issue by tiennou** [libgit2/objective-git#454]
Since commits e1fdaae61f821126ec9b827a77dffe449e127cc7 (**EDIT** because OS X has `-isAbsolutePath`), 8c37f466e3f49bf5000c010be2369fa6d4dd9350 and cb5998978a638c46f9e09b92968414ba3a2d7ee2 (**EDIT** because NS_DESIGNATED_INITIALIZER is not defined), Objective-Git can't build on 10.9. Also, tests can't run because of some Swift code from Nimble and Quick, which prevents building those and thus running tests.

I'm wondering, am I *really* late to the party and is this expected, or should I devote time to try and fix builds/tests on 10.9/Xcode 5.1 ?

**Comment by phatblat** [comment]
This is a good question, which platform and Xcode versions should this project support? #452 requires Xcode 6.3 which needs 10.10 to run (not sure what OS X targets are supported).

**Comment by jspahrsummers** [comment]
We haven't really discussed this formally, but I've generally assumed that all developers are running (or capable of running) the latest version of OS X—and therefore Xcode—especially now that updates are free.

Is there a particular reason to support 10.9?

**Comment by joshaber** [comment]
I agree. Unless there's a compelling reason I think we should only worry about latest OS + dev tools.

**Comment by tiennou** [comment]
For the record, I went along and updated a couple hours after posting this. Then the installer borked my kernel on reboot, and the rest of my weekend was dedicated to restoring from Time Machine. Yay Yosemite, sure beats partying after all ;-).
