### ISSUE TITLE
Extending checkout support

### ISSUE THREAD

**Issue by tiennou** [libgit2/objective-git#457]
I've taken a quick peek at where the upcoming stash support is, and noticed there are a few differences with what I had wrote. It now requires a `git_checkout_options` [structure](https://github.com/libgit2/libgit2/blob/96b82b11c64ffcf00e0d10b1bad1b6d1fbfc896c/include/git2/checkout.h#L251), and I noticed we're woefully under-equipped when it comes to that.

Right now we only support progress & notify callbacks, as well as strategy and notification "flags", but no "paths", and no "labels" (which I think are used for conflicts). And since this structure gets used by cherrypick, merge, reset, revert, stash and submodule, maybe it would be nicer to work on DRYing up those measly 4 parameters we have at the moment before it gets out of hand ;-).

**Comment by tiennou** [comment]
Note that I'm throwing that out to see if you guys already have some plans on how to do that.

What I would do is add a `GTCheckoutOptions` (bike-shedding welcome) value-object with a nice and tasty API to wrap the current uses we have while shielding us from the need to change a bunch of places each time we have to convert users' need to libgit2 `git_checkout_options`.

So, for example, our checkout support would change to :
```
GTCheckoutOptions *options = [blah checkoutOptionsWithStrategy:strategy notifyFlags:flags progressBlock:progress notifyBlock:notify];

BOOL success = [repository checkoutCommit:myCommit options:options error:NULL];
```
or you could customize them before handing those to whatever you're trying to do :
```
GTCheckoutOptions *options = [blah checkoutOptionsWithStrategy:strategy notifyFlags:flags progressBlock:progress notifyBlock:notify];

options.paths = @[@"src", "include"];

GTReference *originMaster = [GTReference referenceByLookingUpReferencedNamed:@"origin/master"];

BOOL success = [repository mergeReference:originMaster options:options error:NULL];
```
(obviously this last example is completely made up, because I don't think we're *that* far in handling merges yet).

**Comment by tiennou** [comment]
Eeek. I don't think it's even sensible to ask for a merge with paths. Let's hope the point gets through anyway :smile:.

**Comment by jspahrsummers** [comment]
Sounds reasonable. We don't use libgit2 checkout ourselves, so I don't feel qualified to comment on the use of its API.
