### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by umutbozkurt** [libgit2/objective-git#465]
Hello, where can one find the documentation?

Thanks

**Comment by joshaber** [comment]
What sort of documentation are you looking for? Most methods and properties are documented in the headers, e.g., https://github.com/libgit2/objective-git/blob/d4e18a9168043f61afaccc2f8035c485a227b533/ObjectiveGit/GTRepository%2BCommitting.h.

**Comment by umutbozkurt** [comment]
Yes figured that out. Also, tests are good to find some examples
thanks
