### ISSUE TITLE
iOS app crashes when launching when not launched from XCode

### ISSUE THREAD

**Issue by jayztemplier** [libgit2/objective-git#490]
Hi,

first of all, thanks for the objective-c wrapper! That's really awesome.

I've been trying to include the library on my iOS project for several days now. I made it working mostly by following the instructions of the iOS example project and enabling the use of non-modular libraries.

I am now facing another problem: when I launch the app from Xcode, everything works perfectly. However, when I launch the application on the simulator without using Xcode, the app crashes right away.
On Device, even with Xcode it doesn't work.

Any idea of what it could be?
Also, as a feature request, having the cartage integration for iOS working would be awesome.

Thanks!

**Comment by phatblat** [comment]
Take a look at your app's console log to see if it's having trouble finding the `ObjectiveGit.framework`. It's possible that the framework isn't getting copied into the bundle and also possible that [it's not finding it](http://stackoverflow.com/questions/24333981/ios-app-with-framework-crashed-on-device-dyld-library-not-loaded-xcode-6-beta).

**Comment by jayztemplier** [comment]
Awesome thanks!  It worked!

Now, I had to manually pick the framework build for debug/iphoneos. Is there a way to automatically embed the right file? (release, simulator etc)

**Comment by phatblat** [comment]
Personally, I'm using [Carthage](https://github.com/Carthage/Carthage) to get around that as it builds a (or downloads a pre-built) fat framework with architectures for both the simulator and devices.

![screen shot 2015-07-17 at 3 34 19 pm](https://cloud.githubusercontent.com/assets/28851/8757658/55ca3012-2c99-11e5-8b35-59868785d924.png)

```bash
lipo -info Carthage/Build/iOS/ObjectiveGit.framework/ObjectiveGit
Architectures in the fat file: Carthage/Build/iOS/ObjectiveGit.framework/ObjectiveGit are: i386 x86_64 armv7 arm64
```

However, if you try to submit an app configured like this to the app store, you'll get rejected for having the simulator slices included. My approach (which hasn't been tested yet) on that is to run [Realm's strip-frameworks.sh](https://github.com/realm/realm-cocoa/blob/master/scripts/strip-frameworks.sh) script.

Another solution for if you've simply added `ObjectiveGitFramework` as a subproject is to use `
$(BUILD_DIR)/$(CONFIGURATION)$(EFFECTIVE_PLATFORM_NAME)` in the path to `ObjectiveGit.framework` as that will automatically resolve to values like `Debug-iphonesimulator` or `Release-iphoneos`, depending on the build destination.

**Comment by jayztemplier** [comment]
Sweet! So I can actually use Cartage for the iOS app? I tried to by following the Mac OS X instruction but it was unsuccessful.

**Comment by phatblat** [comment]
Yes, Carthage works great for adding ObjectiveGit to your project. Take a look at their [iOS setup instructions](https://github.com/Carthage/Carthage#if-youre-building-for-ios) which are great.

Admittedly, our README needs some updates, especially for getting started on iOS.

**Comment by phatblat** [comment]
Re-reading the Carthage setup instructions it looks like the `copy-frameworks` command takes care of stripping the extra architectures out, so that `strip-frameworks.sh` script I linked to is unnecessary.

**Comment by phatblat** [comment]
Closing as it looks like this issue is resolved.
