### ISSUE TITLE
What is the reason of this error ```Command /bin/sh failed with exit code 1```

### ISSUE THREAD

**Issue by xiangism** [libgit2/objective-git#498]
In xcode 6.3, osx10.10, I am building the ```ObjectiveGitFramework.xcodeproj```, It is have only one error

```
Building for x86_64 i386 armv7 armv7s arm64
Building libssh2 for iphonesimulator8.3 x86_64
Please stand by...
/Users/xiangism/work/mac_app/ObjectiveGit-iOS-Example/objective-git/External/libssh2-ios/bin/iphonesimulator8.3-x86_64.sdk/build-libssh2.log
Command /bin/sh failed with exit code 1
```
The context of "build-libssh2.log" is ```Neither libtoolize nor glibtoolize could be found!```. (I had install brew).
How should I do? Thanks~~~

**Comment by pietbrauer** [comment]
You should run [`./scripts/bootstrap`](https://github.com/libgit2/objective-git/blob/master/script/bootstrap) for your first time setup. This should install any dependencies you might have missed.

Does this work for you then?

**Comment by xiangism** [comment]
Yeah, Thanks~~
The problem has been resolved when I run ```/scripts/bootstrap``` again. But I have new problem, I'm running the demo app in IPhone, the error message arises--
```
dyld`dyld_fatal_error:
->  0x1fecd08c <+0>: trap   
    0x1fecd090 <+4>: nop  
```
I think I have not link  my application  to ```libObjectiveGit-iOS.a```, I couldn't find my file, Where can I find it?

**Comment by pietbrauer** [comment]
You can import the Library on iOS the same as on OS X, please find the instructions in the [README](https://github.com/libgit2/objective-git#importing-objectivegit-on-os-x). You can also use Carthage (which downloads it precompiled).
