### ISSUE TITLE
Failed to authenticate SSH session: Waiting for USERAUTH response

### ISSUE THREAD

**Issue by nenadvulic** [libgit2/objective-git#511]
Hello,

i want to clone private repository (ssh://git@bitbucket.org/dump_rs/gullivr.git) hosted in bitbucket using deployment key but i got  Failed to authenticate SSH session: Waiting for USERAUTH response.

    __block GTCredentialProvider *provider = nil;
    provider = [[GTCredentialProvider alloc] init];
    
    provider = [GTCredentialProvider providerWithBlock:^GTCredential *(GTCredentialType type, NSString *URL, NSString *credUserName) {
        GTCredential *cred = nil;
        NSError* error = nil;
        NSURL *public = [NSURL fileURLWithPath:[documentsDirectory stringByAppendingPathComponent:@"publicKey"]];
        NSURL *private = [NSURL fileURLWithPath:[documentsDirectory stringByAppendingPathComponent:@"privateKey"]];
     
        
        cred = [GTCredential credentialWithUserName:@"git"
                                       publicKeyURL:public
                                      privateKeyURL:private
                                         passphrase:@"demopass123"
                                              error:&error];
        
        
        return cred;
    }]

 [GTRepository cloneFromURL:[NSURL URLWithString:@"ssh://git@bitbucket.org/dump_rs/gullivr.git"] toWorkingDirectory:localURL options:@{GTRepositoryCloneOptionsCredentialProvider: provider} error:&error transferProgressBlock:transferProgressBlock checkoutProgressBlock:checkoutProgressBlock];

**Comment by tiennou** [comment]
I think this might help you libgit2/libgit2#3392.

(Also, you alloc+init a provider that you immediately reassign, but that's a minor point ;-))

**Comment by phatblat** [comment]
@nenadvulic make sure that the key you are using is associated with your Bitbucket account. I get the same  "Failed to authenticate SSH session: Waiting for USERAUTH response" message if I use a brand new key.

**Comment by pietbrauer** [comment]
I think this issue can be closed. I saw the same issue when using it with GitHub and the key was not present.

**Comment by white-gecko** [comment]
I also get the message `_pygit2.GitError: Failed to authenticate SSH session: Waiting for USERAUTH response` with the following script:

```
import os
import pygit2

url = "ifigit@git.informatik.uni-leipzig.de:hardwarepraktikum/hwpb.git"        # ssh public

class MyRemoteCallback (pygit2.RemoteCallbacks):
    def credentials(self, url, username_from_url, allowed_types):
        ssh = os.path.join(os.path.expanduser('~'), '.ssh')
        print(ssh)
        pubkey = os.path.join(ssh, 'id_rsa.pub')
        privkey = os.path.join(ssh, 'id_rsa')
        return pygit2.Keypair(username_from_url, pubkey, privkey, "")

repo = pygit2.clone_repository(url, "repo", callbacks=MyRemoteCallback())
```

`id_rsa` and `id_rsa.pub` are just created with `ssh-keygen` and has no password.

Does the SSH connection also ask if for the known hosts?
