### ISSUE TITLE
Switch CI script to xcodebuild + xcpretty

### ISSUE THREAD

**Issue by pietbrauer** [libgit2/objective-git#520]
As discussed in #516 we see some failures with `xctool` in order to avoid that we should change to `xcodebuild` and [`xcpretty`](https://github.com/supermarin/xcpretty) ([optionally](https://github.com/libmx3/mx3/pull/19/files#diff-b67911656ef5d18c4ae36cb6741b7965R35)).

**Comment by phatblat** [comment]
Closing as #516 has addressed the Xcode 7 build issues on Travis
