### ISSUE TITLE
Should `isAGitDirectory` be public?

### ISSUE THREAD

**Issue by samskiter** [libgit2/objective-git#524]
I can't find any use of it. Should it be a public class method of `GTRepository`?

**Comment by joshaber** [comment]
Hah, yeah, and it's almost certainly gonna be wrong in a lot of situations. A PR to :fire: it would be great :smile:

**Comment by samskiter** [comment]
Ah I see. It's an old method. it's not currently public, i just wondered if it should be as it's pretty useful

**Comment by joshaber** [comment]
It seems likely that libgit2 has some function like that that we should use instead.

**Comment by pietbrauer** [comment]
What I did in my app is to check if [`[GTRepository initWithURL:error:]`](https://github.com/libgit2/objective-git/blob/master/ObjectiveGit/GTRepository.m#L179) and check for the `libgit2` error which is returned if it is not a repository. I tried both ways, the `isAGitDirectory` check and checking for the error, they both result in the same behaviour.

**Comment by joshaber** [comment]
Yeah, I'd expect `-initWithURL:error:` to be more future-safe.
