### ISSUE TITLE
dyld: Library not loaded: @rpath/ObjectiveGit.framework/ObjectiveGit 

### ISSUE THREAD

**Issue by zixun** [libgit2/objective-git#526]
I build  objective-git by Carthage as the readme told me, and run it in my iPad Simulator, but it cant run,and the console show as below:

dyld: Library not loaded: @rpath/ObjectiveGit.framework/ObjectiveGit
  Referenced from: /Users/chenyl/Library/Developer/CoreSimulator/Devices/533A4827-3BD7-4ABE-BFDE-B5AF7F87E998/data/Containers/Bundle/Application/431C8BF3-1E5D-477A-8403-BA32F3DDAF52/yomi.app/yomi
  Reason: image not found

**Comment by mdiep** [comment]
Are you sure you followed the `copy-frameworks` step of the Carthage instructions?

That message means that `ObjectiveGit.framework` wasn't copied into your application bundle.

**Comment by zixun** [comment]
@mdiep  yes,im sure

**Comment by mdiep** [comment]
Oh, have you set the `@rpath` value for your application?

You'd need to go to the app target's build settings and look at `Runpath Search Paths`. `@executable_path/../Frameworks` should be one of the values for that setting.

**Comment by pietbrauer** [comment]
@zixun I just faced the same problem in another project with another library somehow during all the Xcode betas it messed up the project and I couldn't get it to work. The workaround for me was to remove the target and create a new one while strange it makes sure all the new Xcode defaults are set correctly.

**Comment by zixun** [comment]
@pietbrauer  thx~ i'll try your idea

**Comment by pietbrauer** [comment]
@zixun any update on this?

**Comment by pietbrauer** [comment]
Closing this as it is most likely solved, feel free to reopen if it still occurs.
