### ISSUE TITLE
Push issue

### ISSUE THREAD

**Issue by RichardLewin87** [libgit2/objective-git#544]
Hi,

I am currently using the library to push to a remote repo after having created one locally. I have linked up the local repo withy the remote repo successfully and created a commit successfully. However, upon trying to push the commit I am getting the following error:

@"Push upload to remote failed".

This is not a blank repo and therefore I need to force the push, however, I cannot figure out how to do this with the library. Due to not being able to force would it explain the error and if so how do I force a push?

Edit:

Currently this is my push line of code:

[self.repo pushBranch:currentBranch toRemote:remote withOptions:@{GTRepositoryRemoteOptionsCredentialProvider: self.credentials} error:&error progress:NULL];

Thanks in advance.

**Comment by pietbrauer** [comment]
So your question is how to do a force push?

**Comment by RichardLewin87** [comment]
Thanks @Piebrauer for your reply. Yes, that was my question but have since figured it out so I will close this now.
