### ISSUE TITLE
Linker errors building ObjectiveGit-iOS with Xcode 7.3

### ISSUE THREAD

**Issue by phatblat** [libgit2/objective-git#546]
These errors appear when building with either 7.3 beta 1 or 2.

![screen shot 2016-01-29 at 7 00 14 am](https://cloud.githubusercontent.com/assets/28851/12677565/247a2f96-c657-11e5-8341-581682433566.png)

```
Undefined symbols for architecture x86_64:
  "_libssh2_userauth_publickey_frommemory", referenced from:
      __git_ssh_authenticate_session in libgit2-ios.a(ssh.c.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by pietbrauer** [comment]
I don't think its an issue per se. I just had this issue when I was compiling `libgit2` using Xcode 7.3 but had `libssh2` compiled using Xcode 7.2 so it wouldn't recompile. I don't think its a general issue.

**Comment by phatblat** [comment]
I'm still getting this from Xcode 7.3 beta 4, but only when building for the iOS Simulator when `libgit2-ios.a` has not been built yet. Building for a device works fine and immediately after that building for the iOS Simulator works.

**Comment by phatblat** [comment]
Can't reproduce these errors in the final build of Xcode 7.3 (7D175).
