### ISSUE TITLE
Release 0.11.0

### ISSUE THREAD

**Issue by pietbrauer** [libgit2/objective-git#560]
As stated in #559 I am kind of depending on Bitcode and better merge conflicts, can someone release a new version?

@mdiep style CHANGELOG:

* Added support for Bitcode (#553, #558). Thanks @phatblat and @pietbrauer!
* Added support for pull operations which result in merge conflicts and added support for merging 2 branches (#559). Thanks @pietbrauer!
* Update dependencies to SSZipArchive, Nimble and Quick (#555, #557). Thanks @phatblat and @pietbrauer!

Thank you to @joshaber and @phatblat for reviewing pull requests! :sparkles:

**Comment by joshaber** [comment]
I'd like to start handing off more of the management of ObjectiveGit to the community who's using it. Do you have the necessary permissions to make a new release? If not, I'll figure out who to talk to to get you that.

**Comment by pietbrauer** [comment]
I have, but until now you or @mdiep were the release masters.

**Comment by joshaber** [comment]
:crown: 

(:point_up: your release master crown)

**Comment by pietbrauer** [comment]
:+1: If I would watch Game of thrones I would post some reference to it here:


(This would be the end of the reference)

Will take care of the release then 👊

**Comment by joshaber** [comment]
![](http://www.reactiongifs.com/wp-content/uploads/2013/03/woo-hoo.gif)

**Comment by pietbrauer** [comment]
Done https://github.com/libgit2/objective-git/releases/tag/0.11.0

**Comment by phatblat** [comment]
A :crown:ing achievement
