### ISSUE TITLE
0.12.0: --no-use-binaries fails with PhaseScriptExecution libssh2-iOS error

### ISSUE THREAD

**Issue by aral** [libgit2/objective-git#568]
Not sure if this is unique to 0.12.0 (as I haven’t tried it with earlier versions), but…

In a fresh sandbox, with the following Cartfile:

`github "libgit2/objective-git" ~> 0.12.0`

## Works:

`carthage bootstrap --platform iOS`

Succeeds (using the 0.12.0 binary).

## Doesn’t work:

`carthage bootstrap --platform iOS --no-use-binaries`

Fails with:

```
 ~/sandbox/test  carthage bootstrap --platform iOS --no-use-binaries
*** No Cartfile.resolved found, updating dependencies
*** Fetching objective-git
*** Checking out objective-git at "0.12.0"
*** xcodebuild output can be found in /var/folders/vp/l22f5841353_6v24wxvpxvw00000gn/T/carthage-xcodebuild.8wFoKx.log
*** Building scheme "ObjectiveGit iOS" in ObjectiveGitFramework.xcworkspace
** BUILD FAILED **


The following build commands failed:
	PhaseScriptExecution libssh2-iOS /Users/aral/Library/Developer/Xcode/DerivedData/ObjectiveGitFramework-cetwdvzstjzbtvgasttncpqwotvf/Build/Intermediates/ObjectiveGitFramework.build/Release-iphoneos/libssh2-iOS.build/Script-6A3C609117D5963700382DFF.sh
(1 failure)
A shell task failed with exit code 65:
** BUILD FAILED **


The following build commands failed:
	PhaseScriptExecution libssh2-iOS /Users/aral/Library/Developer/Xcode/DerivedData/ObjectiveGitFramework-cetwdvzstjzbtvgasttncpqwotvf/Build/Intermediates/ObjectiveGitFramework.build/Release-iphoneos/libssh2-iOS.build/Script-6A3C609117D5963700382DFF.sh
(1 failure)
```

**Comment by pietbrauer** [comment]
@aral Hm, looks strange. `/var/folders/vp/l22f5841353_6v24wxvpxvw00000gn/T/carthage-xcodebuild.8wFoKx.log` should give you a log for the `libssh2` build maybe this contains some pointers?

**Comment by phatblat** [comment]
@aral the [`update_libssh2_ios`](https://github.com/libgit2/objective-git/blob/master/script/update_libssh2_ios) script depends on a few tools which the [`bootstrap`](https://github.com/libgit2/objective-git/blob/master/script/bootstrap) will install for you. However, a Carthage build doesn't trigger our bootstrap, so you'll need to run that at least once to set up the machine.

**Comment by aral** [comment]
@phatblat That sounds like a likely reason :) Will test it out.

If that is the case, would you be open to a pull request with a script that is run in a Run Script task in Xcode that checks for bootstrap requirements and runs the bootstrap script. (There may be issues with this, of course, around permissions and even whether that is an expected side-effect of a carthage build. On the whole, though, the thing I mostly expect a Carthage build to do is to succeed so I don’t have to think about it.) :)

Thoughts? :)

**Comment by phatblat** [comment]
I like the idea. The bootstrap script would need to be hooked into both the iOS and Mac builds so that it runs at least once regardless of which platform is being built.

[`bootstrap`](https://github.com/libgit2/objective-git/blob/master/script/bootstrap) will need some review to ensure it doesn't fail builds if it's going to run every time. I believe it bails if some tools are not installed, but some aren't require for a normal build (e.g. `xctool`). When we last discussed it in #497, some users don't have homebrew installed, so the script is designed to stop and inform the user in a case like that (which would also fail the build if hooked up in this way).

**Comment by phatblat** [comment]
Just ran into this myself on a fresh macOS Sierra box on which `bootstrap` hadn't been run yet. The iOS `build-libssh2.log` file contains the following message.

> Neither libtoolize nor glibtoolize could be found!

**Comment by pietbrauer** [comment]
@aral @phatblat closing this as there is no new information. Feel free to reopen.
