### ISSUE TITLE
Make GTReflog's initWithReference public

### ISSUE THREAD

**Issue by Uncommon** [libgit2/objective-git#578]
`-[GTRefLog initWithReference:]` is in GTReflog+Private.h for reasons that are not clear to me. I've found a situation where I want to use it, so I ended up writing a category interface to expose it since I can't access that header from the framework.

My situation is that I want to get information about a specific stash, so I'm imitating what's in `git_stash_foreach`, except using ObjGit classes and using a specific index instead of iterating over all stashes.

I'll gladly do a pull request, but I wanted to make sure there isn't an alternative that I missed.

**Comment by pietbrauer** [comment]
I don't see a reason why it should be `private`, would be happy if you would do a PullRequest.

**Comment by pietbrauer** [comment]
Closed via #596
