### ISSUE TITLE
Why no GTRemote.updatePushURLString:?

### ISSUE THREAD

**Issue by Uncommon** [libgit2/objective-git#583]
Is there any particular reason why GTRemote has updateURLString but no updatePushURLString?

I'll gladly do a pull request. It looks pretty straightforward.

**Comment by phatblat** [comment]
There's -setPushURLString: Does that do what you want?

-- 
Ben Chatelain
Sent with Airmail

**Comment by Uncommon** [comment]
Aha, yes. I think when I saw updateURLString, then I assumed that pushURLString was a read-only property.

So why do we have both setURLString and updateURLString?

**Comment by phatblat** [comment]
Looks like the -set methods (property accessors) completely ignore any errors, but updateURLString checks for an error and returns NO when the update failed.

**Comment by Uncommon** [comment]
Looking at the history, apparently the writable version of the properties was added later. I think it would be good to have updatePushURLString, both for completeness and because it's good to know about errors. I'll go ahead and do that.

**Comment by Uncommon** [comment]
Done in #585
