### ISSUE TITLE
Nimble is missing

### ISSUE THREAD

**Issue by Uncommon** [libgit2/objective-git#584]
I went to run the unit tests, but found that Nimble was missing. I updated the submodules and re-ran `script/bootstrap`, to no avail. Finally I installed Carthage manually and did `carthage update`, but the build for Quick-tvOS failed, which apparently aborts the whole process and Xcode still says "No such module 'Nimble'".

Does the Carthage stuff need to be added to bootstrap? Or is there something else I need to do to get this working?

This is after updating to master at 5e244391450bb35c2c8e7b2be37426da390937ba

**Comment by Uncommon** [comment]
Also, running `carthage update` changed some files:

```
diff --git a/Cartfile.resolved b/Cartfile.resolved
index b67d877..18f899c 100644
--- a/Cartfile.resolved
+++ b/Cartfile.resolved
@@ -1,4 +1,4 @@
-github "Quick/Nimble" "v4.0.0"
+github "Quick/Nimble" "v4.1.0"
 github "Quick/Quick" "v0.9.2"
-github "ZipArchive/ZipArchive" "v1.1"
+github "ZipArchive/ZipArchive" "v1.3"
 github "jspahrsummers/xcconfigs" "0.9"
diff --git a/Carthage/Checkouts/Nimble b/Carthage/Checkouts/Nimble
index 29f7fb3..b4a0f9d 160000
--- a/Carthage/Checkouts/Nimble
+++ b/Carthage/Checkouts/Nimble
@@ -1 +1 @@
-Subproject commit 29f7fb3732893f76fa851cb37b0c4b339c49cead
+Subproject commit b4a0f9d6ee6b89f0e2f9ee8fa32aaa7200b1e27c
diff --git a/Carthage/Checkouts/ZipArchive b/Carthage/Checkouts/ZipArchive
index 057c493..f420e47 160000
--- a/Carthage/Checkouts/ZipArchive
+++ b/Carthage/Checkouts/ZipArchive
@@ -1 +1 @@
-Subproject commit 057c4937552f421d782e6d07ae09191b191bcc23
+Subproject commit f420e47ea5c3808f5efcedd8aa542f506dfe0a17

```

**Comment by Uncommon** [comment]
I tried building and copying Nimble.framework manually, but then had the same errors for Quick. I copied that one too, and then ZipArchive was missing.

**Comment by pietbrauer** [comment]
@Uncommon Shouldn't #585 fail if nimble would be missing? The setup of this repository can be tricky sometimes and I suspect something to be wrong on your machine, at least that would indicate why #585 is succeeding.

**Comment by Uncommon** [comment]
Yeah, I wasn't able to run the tests locally, but I got the travis build to pass without too much trial and error.

I tried on a different machine and had the same tvOS failure. I see that Nimble & Quick are not subprojects; how are they supposed to get built?

**Comment by pietbrauer** [comment]
Stupid question, but did you use the Xcode Workspace?

**Comment by Uncommon** [comment]
Well since the answer is no, I think it wasn't a stupid question :)

I forgot there was a workspace; I've just been using the project as a subproject. So it does work if I run the tests from the workspace. Should I expect it to work just with the project, or is that not a goal?

**Comment by pietbrauer** [comment]
No, shouldn't work that's why the workspace is there. You might need to link all the frameworks in your project as well, if this is the problem.

Closing this as solved then 😊
