### ISSUE TITLE
Unable to clone from some SSH services

### ISSUE THREAD

**Issue by pietbrauer** [libgit2/objective-git#586]
I am unable to clone a repository from Visual Studio Team Services via SSH as objective-git fails with

```
Error Domain=GTGitErrorDomain Code=-1 "Failed to clone repository from ssh://git2go@git2go.visualstudio.com:22/MyFirstProject/_git/git2go-com to file:///.../ssh/_git/git2go-com/" UserInfo={NSLocalizedDescription=Failed to clone repository from ssh://git2go@git2go.visualstudio.com:22/MyFirstProject/_git/git2go-com to file:///.../ssh/_git/git2go-com/, NSUnderlyingError=0x7ff7d1f2a1d0 {Error Domain=GTGitErrorDomain Code=-1 "Failed to start SSH session: Unable to exchange encryption keys" UserInfo={NSLocalizedDescription=Failed to start SSH session: Unable to exchange encryption keys}}}
```

When I clone the same repository with the same keys via command-line `git` it clones successfully, which means the key is valid and there is something wrong with how we handle SSH authentication.

There are other installations of git servers with SSH that have problems as well, but I was unable to reproduce them.

Visual Studio fails reliable so I thought I would open an issue. I know that @tiennou worked on the SSH implementation, but maybe someone else has insights into this topic as well?

**Comment by tiennou** [comment]
It seems to fail inside `_libssh2_kex_exchange`, but I honestly have no idea why. There have been [some](http://trac.libssh2.org/ticket/83) [sightings](http://trac.libssh2.org/ticket/51) of that error (from the PHP bindings), but they're year-old. There's [this](http://trac.libssh2.org/ticket/305), 1 year old, with some steps on debugging, so you might try that and get more information out of `libssh2`

**Comment by pietbrauer** [comment]
I suspect somethings wrong on our Objective-C side as it is working for Working Copy which uses `libgit2` directly. I will do some digging how the other adapters handle SSH connections.

**Comment by tiennou** [comment]
Just noticed that, given the recent TLS-pocalypse, it might be related to us tracking an old version of libssh2 at the time this was filed. Does it still happen with current master ?

**Comment by tiennou** [comment]
AFAIK there are no libgit2 reports that seem to point to a missing key exchange/support from the currently in-use libssh2, and since this report is pretty old, let's say it's now fixed 😉.
