### ISSUE TITLE
Umbrella Header for Module does not include header

### ISSUE THREAD

**Issue by jaredjones** [libgit2/objective-git#588]
OS: macOS Sierra 10.12
Version: 0.12.0
Xcode 8.x Beta
A compiler warning is thrown because the module-map is linking in files that do not exist for the given paths.

/Users/jaredjones/Developer/BugSplat/Bug Splat (Server)/<module-includes>:1:1: Umbrella header for module 'ObjectiveGit' does not include header '/git2/sys/git2/sys/merge.h'

/Users/jaredjones/Developer/BugSplat/Bug Splat (Server)/<module-includes>:1:1: Umbrella header for module 'ObjectiveGit' does not include header '/git2/sys/merge.h'

**Comment by pietbrauer** [comment]
@jaredjones are you able to work with it now? I don't have this issue myself.

**Comment by aral** [comment]
I’m also seeing this on Xcode 8.2.1 on a Swift 3 project.

**Comment by mssun** [comment]
Same with me.
