### ISSUE TITLE
tvOS Support

### ISSUE THREAD

**Issue by kconner** [libgit2/objective-git#592]
I want to use ObjectiveGit to fetch and display data from a Git repo in a tvOS app.

I'll give this a try myself if I find time, but for the moment I'm just registering interest.

---

My goal is to use GitHub as kind of a publishing platform for static app content. The format of the app is a bit like a photo blog. It's a showcase for side projects that my coworkers and I are working on.

So I intend to use:

- Pull requests for reviewing new content
- A simple file system pattern that my non-tech peers can use to submit new content
- A branch for public content, a branch for staging
- Clone / pull for local caching and delta updates

ObjectiveGit looks like just the right thing to use, but of course this needs to be a TV app.

**Comment by pietbrauer** [comment]
I had a go with tvOS some time ago, I believe I still have a branch open on my fork. It has been quite tricky to do and I wasted around a week on it. Maybe I am missing something crucial and you are more lucky.

**Comment by Uncommon** [comment]
Another option might be to use the GitHub API to access content, rather than cloning the repository onto the device, especially if space is a concern.

**Comment by pietbrauer** [comment]
Yeah, especially since you don't have a persistent documents directory and your tmp directory gets nuked once every few uses.

**Comment by kconner** [comment]
You make good points. Delta updates don't make much sense if the OS would necessitate frequent cloning anyway.
