### ISSUE TITLE
Build error on Travis CI

### ISSUE THREAD

**Issue by thomaspaulmann** [libgit2/objective-git#595]
I use Carthage to include Objective Git in my project [Up N Down](https://github.com/up-n-down/Up-N-Down). Unfortunately travis is failing all the time caused on an error during `xcodebuild` of Objective Git with [exit code 65](https://travis-ci.org/up-n-down/Up-N-Down/builds/170075508). 

Do you have any experience with this kind of error?

It doesn't matter if I use `carthage bootstrap`or `carthage update`.

**Comment by pietbrauer** [comment]
Shouldn't Carthage use the binary?

**Comment by thomaspaulmann** [comment]
Locally it does, on Travis it doesn't. So you haven't experience with that kind of error? Than I will forward it to the Carthage colleagues :-)

**Comment by pietbrauer** [comment]
You can use a `GITHUB_ACCESS_TOKEN` environment variable. Travis gets rate limited by the GitHub API so Carthage falls back to building it. Setting a personal access token as a __secret__ environment variable should do the trick.

**Comment by thomaspaulmann** [comment]
Thanks for the suggestion! I'll give it a try and close the ticket as soon as the CI runs correctly. Sorry for bothering you instead of Carthage :-P

**Comment by thomaspaulmann** [comment]
Yeah, everything works fine after adding the github token and travis is greem again. Thank you very much!
