### ISSUE TITLE
IPv6 crashed

### ISSUE THREAD

**Issue by WangHengHeng** [libgit2/objective-git#600]
I used `github "libgit2/objective-git" "0.12.0"` in `Cartfile.resolved` file, upload for appStore then get the bellow Rejetion!

> Performance - 2.1
>Your app crashed on iPhone running iOS 10.1.1 connected to an IPv6 network

Hope for your attention ~

**Comment by pietbrauer** [comment]
You usually get these rejections if you are hardcoding an `IPv4` IP address in your app. I am releasing Git2Go with `0.12.0` as well and have no issues.

**Comment by WangHengHeng** [comment]
My fault ~
