### ISSUE TITLE
ObjectiveGit.framework

### ISSUE THREAD

**Issue by xiaojinjinjin** [libgit2/objective-git#614]
What problem to download is too slow

**Comment by pietbrauer** [comment]
Can you describe the problem in a bit more detail, please? Are you referring to the GitHub Download or a Clone operation?

**Comment by xiaojinjinjin** [comment]
In the GitHub download ObjectiveGit.framework is not respond

**Comment by pietbrauer** [comment]
Closing in favor of #616
