### ISSUE TITLE
Downloading objective-git.framework 

### ISSUE THREAD

**Issue by xiaojinjinjin** [libgit2/objective-git#616]
Downloading objective-git.framework binary at "0.12.0"
GitHub API request failed: NetworkError(Error Domain=NSURLErrorDomain Code=-1001 "The request timed out."

**Comment by pietbrauer** [comment]
I think this is something related to your connection to GitHub.com or possibly the asset server the binary is stored on (wild guess). Can you download other Carthage framework binaries?

**Comment by xiaojinjinjin** [comment]
Other Carthage framework available for download.Only this  objective-git.framework can't download,why？？

**Comment by pietbrauer** [comment]
Hey, at this point I don't know of any more ways to help you. Can you download directly by clicking on the zip file in [releases](https://github.com/libgit2/objective-git/releases)? The download is also 26 MB whereas other frameworks are relatively small, maybe this is an issue?

**Comment by kedu** [comment]
i'm sorry,before i had not see this issue.now i download zip,but when i had add objective-git Folder to my target,it's also report an error,other file is not found,does it also depend othen module? in the end ,please tell me how to use it correct,thanks!

**Comment by pietbrauer** [comment]
I will look into this in Sunday. As my project has no issues download from GitHub I suspect either the Carthage version or your location (different CDN provider?!) to be the issue. Are you both in Japan?

**Comment by kedu** [comment]
Carthage version is 0.18.1,i live at China.

**Comment by pietbrauer** [comment]
My guess is that this has something to do with GitHub and the CDN involved. AFAIK releases are hosted on Amazon S3. My tip would be to download it manually if the download fails. I can see nothing wrong with the ZIP itself. Some other projects also suffer from this: https://github.com/realm/realm-cocoa/issues/2713#issue-112458107.

My advice would be to try a different DNS and/or a VPN when using Carthage from China.
