### ISSUE TITLE
I have something wrong with Manual install.

### ISSUE THREAD

**Issue by freedani** [libgit2/objective-git#617]
I try installing in manual.

```
1. Download the latest ObjectiveGit.framework.zip from releases.
2. Unzip the file.
3. Follow the Carthage instructions #3 or #4, depending on platform.
```

After I have done steps above, and open .xcodeworkspace file. There is an error. File <ObjectiveGit/ObjectiveGit.h> not found.

I add Carthage/Build/iOS/ObjectiveGit.framework into the project folder and the error disappeared.

I suggest that update [readme.md](https://github.com/libgit2/objective-git#manual) to make more people know how to use it easily.

**Comment by pietbrauer** [comment]
Hey @freedani,

thanks for opening an issue. The provided Carthage framework is to be used with the Carthage Command Line Application only. It (Carthage and the Documentation) expects the frameworks to be in this exact location. Please have a look at the [Carthage Documentation](https://github.com/carthage/carthage#adding-frameworks-to-an-application) on how to add frameworks to your application (via `Cartfile`)

**Comment by freedani** [comment]
Hey @pietbrauer ,
thanks for your reply. I can't not add framework to my application via `Carthage` with the error log
```
Caught signal triggered by the Swift runtime!
Illegal instruction

Unfortunately, this is probably a bug in Swift and not Carthage. If
this is preventing you from doing work, please file an issue and we'll
do our best to work around it:
https://github.com/Carthage/Carthage/issues/new

Please also consider filing a radar with Apple, containing the version
of Carthage and any crash report found in Console.app.
```
I google it and cannot find the solution so I install it manual.

**Comment by pietbrauer** [comment]
What does your `Cartfile` look like?

**Comment by freedani** [comment]
`Carthage version` : 0.19.1
`xcodebuild -version`: Xcode 8.2 Build version 8C38
Are you using --no-build? no
Are you using --no-use-binaries? no
Are you using --use-submodules? no

Cartfile
```
github "libgit2/objective-git"
```
