### ISSUE TITLE
GTRepositoryCloneOptionsCheckout are missing

### ISSUE THREAD

**Issue by slavikus** [libgit2/objective-git#618]
@tiennou, we have lost `GTRepositoryCloneOptionsCheckout` constant — it's declared in the `GTRepository.h` file, but nowhere else, so if any third-party code attempts to use it, we get a link error saying it's not defined anywhere. Not sure if the relevant code is also gone or substituted by `GTCheckoutOptions` struct.

**Comment by tiennou** [comment]
IIRC I removed it in favor of some other option. If that's the case, it can go away.
