### ISSUE TITLE
GTRepository leaks memory

### ISSUE THREAD

**Issue by r-zawislak** [libgit2/objective-git#637]
Hi, I'm using this library in my swift project and I noticed that my app is leaking memory because of it.

To test it out I created a new project and these few lines are leaking memory.

```
while true {
     let repository = try? GTRepository(url: url)
}
```

**Comment by pietbrauer** [comment]
Could you give an example?

**Comment by r-zawislak** [comment]
@pietbrauer I added the code to my issue. Thanks for a reminder. ;)

**Comment by pietbrauer** [comment]
Did you profile it using Instruments?

**Comment by r-zawislak** [comment]
Yes I did use it. I used it determine what caused the leaking and all of them are coming from objective-git. Later on I created a new project to make sure it was true and it was.

**Comment by r-zawislak** [comment]
After doing this for 3 seconds

```
while true {
   let repository = try! GTRepository(url: url)
   let branch = try! repository.currentBranch()
   let commit = try! branch.targetCommit()
   let tree = commit.tree
}
```

![zrzut ekranu 2017-10-03 o 13 19 32](https://user-images.githubusercontent.com/28671384/31122925-1e9b7e3e-a83e-11e7-9247-a3f1eafedfcb.png)

But if I use ```autoreleasepool``` everything is ok. Should it be that way or is it a problem with library?
