### ISSUE TITLE
[iOS] Unable to clone from ssh repositories

### ISSUE THREAD

**Issue by wadxm** [libgit2/objective-git#640]
Hi, I'm trying to clone from a ssh repository with objective-git, but it failed with an "unsupported URL protocol" error, here's my code:

`NSError *error;
GTRepository *repo = [GTRepository cloneFromURL:[NSURL URLWithString:@"ssh://git@xxx.org/xxx"] toWorkingDirectory:directoryPath options:nil error:&error transferProgressBlock:nil];`

After running, repo will be nil and here is the content of error:

Error Domain=GTGitErrorDomain Code=-1 "Failed to clone repository from ssh://git@code.byted.org/ugc/AWELocalizations to file:///var/mobile/Containers/Data/Application/6BEF1FF1-94DB-4D01-8AD9-EA1E51937195/Documents/AWELocalizations" UserInfo={NSLocalizedDescription=Failed to clone repository from ssh://git@code.byted.org/ugc/AWELocalizations to file:///var/mobile/Containers/Data/Application/6BEF1FF1-94DB-4D01-8AD9-EA1E51937195/Documents/AWELocalizations, NSUnderlyingError=0x1d40562c0 {Error Domain=GTGitErrorDomain Code=-1 "unsupported URL protocol" UserInfo={NSLocalizedDescription=unsupported URL protocol}}}

I'm wondering what's wrong with my configurations, thanks a lot :-)

**Comment by tiennou** [comment]
This error message usually means `libssh2` (which is what `libgit2` uses for SSH transport) is not available.

**Comment by Maxwin-z** [comment]
the same error, how to fix it?

**Comment by tiennou** [comment]
You need to compile libgit2 with SSH support enabled, which entails having libssh2 installed as well. Normally `./script/bootstrap` & `./script/update_libgit2` are the scripts that take care of setting up dependencies.

**Comment by wadxm** [comment]
I have tried recompiling libssh2 but the error still occurs, so finally I directly download the complied framework and embed this one in my project

**Comment by tiennou** [comment]
Strange… Can you check the output of [git_libgit2_features](https://libgit2.github.com/libgit2/#HEAD/group/libgit2/git_libgit2_features) to make sure the SSH support is enabled in your build ?

**Comment by Maxwin-z** [comment]
As @wadxm mentioned, I use `Carthage` embed the framework, and fixed the problem.

**Comment by tiennou** [comment]
Glad to hear you've got it working. #643 has updated libssh2 to 1.8.0, which works against the "new" GitHub cryptosuite.
