### ISSUE TITLE
Failed to clone repository .... Underlying error: Failed to start SSH session

### ISSUE THREAD

**Issue by snakelab** [libgit2/objective-git#641]
Hi Folks,

i am using an app and got this errormessage, maybe you can help with this message:

Failed to clone repository .... Underlying error: Failed to start SSH session: Unable to exchange encryption keys

Does anyone here have a tip for me?

thanks

hartmut

![image](https://user-images.githubusercontent.com/2159159/35733970-c5c846b0-081f-11e8-9c5e-41fa7ae18a88.png)

**Comment by tiennou** [comment]
#643 has updated libssh2 to 1.8.0, which works against the "new" GitHub cryptosuite. You should check with the app's developer so it updates its Objective-Git framework. In the meantime, I'm closing the issue, but feel free to reopen !

**Comment by snakelab** [comment]
Hi Etienne, 
thanks.
hartmut
