### ISSUE TITLE
Connecting to github broken due to outdated libssh2

### ISSUE THREAD

**Issue by larsthegeek** [libgit2/objective-git#644]
Github has deprecated a number of crypto protocols that are used in the 5 year old version of libssh2 (@ficfa55) referenced by objective-git.  See [https://githubengineering.com/crypto-deprecation-notice/](url)

This is causing **Unable to exchange encryption keys** errors preventing the ssh session from being established.  This is likely the root cause of the issue for #641 as well.  (In fact, I believe he may be experiencing problems with the same app that I am, passforios [https://github.com/mssun/passforios](url).

I don't program for iOS so I don't have the toolchain to provides a pull request.

**Comment by tiennou** [comment]
#643 has updated libssh2 to 1.8.0, which works against the "new" GitHub cryptosuite. Unless you find it's still not working, I'm closing this. Thanks for the report !
