### ISSUE TITLE
Merging with a custom merge driver

### ISSUE THREAD

**Issue by jonsongoffwhite** [libgit2/objective-git#656]
There is a merge driver present in my repository, which is set up in config and attributes, and it works correctly via the command line, however when merging using `repo.mergeBranch()`
(`- (BOOL)mergeBranchIntoCurrentBranch:(GTBranch *)fromBranch withError:(NSError **)error;`), 
the merge driver doesn't seem to be used.

Am I missing something, or is this something that's not implemented?

Thanks!

**Comment by tiennou** [comment]
AFAIK there's no automatic support in libgit2, so you'll have to grab the interesting parts of [git2/sys/merge.h](https://github.com/libgit2/libgit2/blob/HEAD/include/git2/sys/merge.h) to make it work.

**Comment by jonsongoffwhite** [comment]
@tiennou thanks for the reply!

I'm afraid I'm not well versed with libgit2, could you give me any pointers as to where to start?

**Comment by tiennou** [comment]
You might be able to get more help from StackOverflow (as in, most of the developers follow the libgit2 [tag](https://stackoverflow.com/questions/tagged/libgit2)).

Note that I've never used that part of the code too, so YMMV.

You'll need to declare your own `static git_merge_driver my_driver` struct somewhere, with its `apply` member pointing to your own `git_merge_driver_apply_fn`-style function, and register that using `git_merge_driver_register` (mind your threading), using your "attribute" name as the registration name.

Your apply function should now get called when merging files with the attribute you want (I think this is automatic, but I sincerely don't know), so for now return `GIT_EPASSTHROUGH` so the normal "text" driver does. Make sure this works.

Then, it should be just a matter of using the apply function parameters, most notably the `git_merge_source`, which has all the mergy requirements (eg. ours/theirs, see [git_index_entry](https://libgit2.github.com/libgit2/#HEAD/type/git_index_entry)). You should be able to extract the relevant command to execute from the repo config, and perform a fork/exec dance or something.

HTH!

**Comment by jonsongoffwhite** [comment]
Thanks, that definitely helped!

What do you mean by my "attribute" name?

**Comment by tiennou** [comment]
Not sure, actually 😆. I was under the impression you would have to declare a .gitattributes pattern for which files should be merged with a custom driver, but the docs [explicitely](https://git-scm.com/docs/gitattributes#_defining_a_custom_merge_driver) say it's unrelated to attributes.

Well, I'm confused now. It [seems](https://git-scm.com/docs/gitattributes#_performing_a_three_way_merge) you have to add a `merge=driver_name` attribute to a pattern in .gitattributes so the Thing Happens.

**Comment by tiennou** [comment]
Closing because AFAIK it's not really an issue. Feel free to reopen though !
