### ISSUE TITLE
The 0.14.0 release doesn't support SSH?

### ISSUE THREAD

**Issue by mssun** [libgit2/objective-git#657]
I am using 0.14.0 release and found that SSH protocol is no long supported.

refer: https://github.com/mssun/passforios/issues/186

**Comment by tiennou** [comment]
Sorry about that, this is a duplicate of #645 (which was about updating libgit2 itself, but that's when the issue became apparent). TL;DR is that `libgit2` CMake file is confused by the 4-way iOS arch static link of libssh2 against OpenSSL.

**Comment by mssun** [comment]
Thanks you @tiennou. I did read the CMake file and found that the GIT_SSH flag is not properly set. However, I don't know how to fix it right now. Could you please fix it in the latest PR? Thanks.

**Comment by tiennou** [comment]
We've just released [0.14.1](https://github.com/libgit2/objective-git/releases/tag/0.14.1), which should fix this issue, so I'm closing this. Feel free to reopen if applicable, and thanks for the report !
