### ISSUE TITLE
Automatically resolve merge conflicts with the "newest"

### ISSUE THREAD

**Issue by jeffreybergier** [libgit2/objective-git#665]
Hi,

I'm very new to ObjectiveGit/libgit2. I also would consider myself a novice git user. I'm trying to implement a really simple file based sync system in a demo app. I am able to get everything (configure remote, fetch, pull, push, etc) working as long as there are no merge conflicts. However, I can't seem to find an easy way to get around a merge conflict.

I'm using `- (BOOL)pullBranch:(GTBranch *)branch fromRemote:(GTRemote *)remote withOptions:(NSDictionary * _Nullable)options error:(NSError **)error progress:(GTRemoteFetchTransferProgressBlock _Nullable)progressBlock;` on `GTRepository` or `- (BOOL)mergeBranchIntoCurrentBranch:(GTBranch *)fromBranch withError:(NSError **)error;` and they both fail with the same merge conflict error.

I saw that there is `GTCheckoutStrategyType` which has `useOurs` and `useTheirs` options which seems like it would solve my problem however, that only works on checkouts and I don't know how a checkout would help me in this situation as I'm trying to merge.

I humbly ask for any guidance you can provide. I basically need a super simple and super naive way to resolve merge conflicts. Like I said, something as simple as 'use newest modification' or 'use newest commit' would be great. But even just using 'useTheirs' / 'useOurs' would be an acceptable workaround for me now while I'm learning the system.

Thanks a lot,
Jeff

**Comment by jeffreybergier** [comment]
Hi @tiennou

Thanks so much for answering this and for such a thoughtful response. I’m going to investigate the enumeration and see if I can get it to work. 

I’ll follow up here. I definitely want to write some example documentation if I can get this to work :)

-Jeff

**Comment by jeffreybergier** [comment]
@tiennou it looks like I need to learn how to do a simple fast forward merge before I do any conflict resolution? I’m referring to the example you linked. It has a fairly simple fast forward function. It’s the raw libgit2 code. But hopefully I can replicate it in ObjectiveGit.

**Comment by tiennou** [comment]
That shouldn't be necessary, as `-mergeBranchIntoCurrentBranch:` should already handle everything (though one difference it has with the libgit2 example is that it does it in a roundabout way by first merging the trees in an in-memory index, which it discards in case of conflicts).

If the merge failed because of conflicts, you should have got back [an error](https://github.com/libgit2/objective-git/blob/master/ObjectiveGit/GTRepository+Merging.m#L131) with the conflicted paths.

After your pull call failed, you should really have an index with conflicts, and (if I'm not completely wrong with how conflicts are resolved), you should reenumerate on them and resolve them by re-adding the `ours`/`their` you prefer, then perform the commit with the correct parents (one is the OID of the remote you're pulling, the other is your current HEAD OID), update the current branch to point to the new commit, and profit!… Hopefully.

**Comment by jeffreybergier** [comment]
@tiennou interesting. After I do the pull, even if there are no conflicting files, I get a merge conflict because a fast forward merge needs to happen. I guess I should ask, what order should I be doing these in?

right now I'm doing (and this happens right after a local commit is created and written to the index):
```
            let remote: GTRemote = try self.remote()
            try type(of: self).fetch(remote, self.repo, self.provider)
            try type(of: self).pull(remote, self.repo, self.provider)
            try type(of: self).push(remote, self.repo, self.provider)
```

should I be doing, fetch, pull, merge, push? Or some other order?

**Comment by jeffreybergier** [comment]
I can add a little more info now. If I do the following:
Fetch, Pull, Push and there is a local commit and remote commit (but no files conflicting), then the pull fails with error -13. When I detect that, if I do `git status` on the repo in terminal it says the following:
```
jeffreybergier@Pinkinium ~/L/G/V/HPData> git status
On branch master
Your branch and 'origin/master' have diverged,
and have 1 and 1 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)

All conflicts fixed but you are still merging.
  (use "git commit" to conclude merge)

Changes to be committed:

	modified:   4E35FADD-D174-404E-AEC2-0498CD937A1C.hpwebsite/payload.plist
```

so I thought, aha! if I create commit when I detect this error -13, that will resolve the issue and it mostly does. But now when I type git status I get this output:
```
jeffreybergier@Pinkinium ~/L/G/V/HPData> git status
On branch master
Your branch is up to date with 'origin/master'.

All conflicts fixed but you are still merging.
  (use "git commit" to conclude merge)

```

so I'm going to see if there a method I'm missing to "conclude" the merge.

**Comment by jeffreybergier** [comment]
@tiennou thanks for that info. For a non-conflicting merge (error -13) I was not able to get the cleanupStateWithError to help. It still left the repo in a bad state. But if I do the new commit and then use that method it does cleanup the state and the repo works and can be pushed.

I can make a separate issue for my next problem. Or I can just leave it here. But when there is a conflict that can't be automatically merged (when I change the exact same line of the file remotely and locally and then try to sync) the `-[GTIndex enumerateConflictedFilesWithError:usingBlock:]` indeed enumerates the problem file. However using `-[GTIndex addEntry:error:]` with the index I decided on (I'm just hardcoding it to ours for now) doesn't do anything. Now I found that I can use `-[GTIndex addFile:error:]` and that does actually chooses the file, but the file is broken because it has GIT added markings with <<<<< HEAD and other annotations in the file that preserve both changes but that breaks the file. Could you give more advice on how to use `-[GTIndex addEntry:error:]` to choose the OUR side version and commit the changes?

Thanks!

**Comment by tiennou** [comment]
I'd suggest posting questions to [StackOverflow](https://stackoverflow.com/questions/tagged/objective-git), as it's likely you'd have more visibility with conflict resolution.

**Comment by jeffreybergier** [comment]
@tiennou thanks for the advice. I posted here if anyone has any input: https://stackoverflow.com/questions/51977074/objectivegit-resolving-file-conflicts-with-gtindex-enumerateconflictedfilesw

**Comment by tiennou** [comment]
Closing in favor of SO question. I didn't have the time to take a look at the specifics of merging, so I'm unable to help more.
